apiVersion: apps/v1
kind: Deployment
##This section includes the deployment name and how it connects to 
##other resources using the dictionary <<app>>.
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: frontend
##The deployment specifications and how it operates.
spec:
  selector:  #The list of arrays under selector is taken from the 
            #pod-definition file
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      -  name: nginx
         image: nginx
