apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-jenkins-deployment
  labels:
    app: jenks-deploy
    type: frontend
spec: 
  selector:
    matchLabels:
      app: jenks-deploy
      type: frontend
  replicas: 2
  template:
    metadata:
      name: myapp-jenkins-pod
      labels:
        app: jenks-deploy
        type: frontend
    spec:
      containers:
        - name: jenkins-container
          image: jenkins/jenkins:lts-jdk11
