apiVersion: v1
kind: Service
metadata:
  name: myapp-jenkins-service
spec:
  type: NodePort
  selector:
    app: jenks-deploy
    type: frontend
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30006
